DROP TABLE IF EXISTS financial_forecast CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS expense CASCADE;
DROP TABLE IF EXISTS financial_operation CASCADE;
DROP TABLE IF EXISTS total_per_period;
DROP TABLE IF EXISTS product_per_period;
DROP TABLE IF EXISTS expense_per_period;

CREATE TABLE IF NOT EXISTS financial_forecast
(
    id                         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                       VARCHAR NOT NULL,
    selling_in_credit_rate     FLOAT   NULL,
    building_deprecation_rate  FLOAT   NULL,
    equipment_deprecation_rate FLOAT   NULL
);

CREATE TABLE IF NOT EXISTS product
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    financial_forecast_id BIGINT  NULL,
    unit                  VARCHAR NULL,
    name                  VARCHAR NOT NULL,
    tax                   FLOAT   NOT NULL,
    stock_reserve_rate    FLOAT   NULL,
    FOREIGN KEY (financial_forecast_id)
        REFERENCES financial_forecast (id)
);

CREATE TABLE IF NOT EXISTS financial_operation
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    financial_forecast_id BIGINT  NULL,
    type                  VARCHAR NOT NULL,
    subtype               VARCHAR NULL,
    tax                   FLOAT   NULL,
    FOREIGN KEY (financial_forecast_id)
        REFERENCES financial_forecast (id)
);

CREATE TABLE IF NOT EXISTS total_per_period
(
    financial_operation_id BIGINT NOT NULL,
    year                   INT    NULL,
    sum                    FLOAT  NULL,
    FOREIGN KEY (financial_operation_id)
        REFERENCES financial_operation (id)
);

CREATE TABLE IF NOT EXISTS product_per_period
(
    product_id    BIGINT NOT NULL,
    quantity      INT    NULL,
    for_export    FLOAT  NULL,
    price         FLOAT  NULL,
    cost_per_item FLOAT  NULL,
    year          INT    NULL,
    FOREIGN KEY (product_id)
        REFERENCES product (id)
);