DROP TABLE IF EXISTS financial_forecast CASCADE;
DROP TABLE IF EXISTS product CASCADE;
DROP TABLE IF EXISTS expense;
DROP TABLE IF EXISTS product_per_period;

CREATE TABLE IF NOT EXISTS financial_forecast
(
    id                         BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    name                       VARCHAR NOT NULL,
    selling_in_credit_rate     FLOAT   NULL,
    building_deprecation_rate  FLOAT   NULL,
    equipment_deprecation_rate FLOAT   NULL
);

CREATE TABLE IF NOT EXISTS product
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    financial_forecast_id BIGINT       NULL,
    unit                  VARCHAR      NULL,
    name                  VARCHAR(255) NOT NULL,
    tax                   FLOAT        NOT NULL,
    stock_reserve_rate    FLOAT        NULL,
    FOREIGN KEY (financial_forecast_id)
        REFERENCES financial_forecast (id)
);

CREATE TABLE IF NOT EXISTS expense
(
    id                    BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    financial_forecast_id BIGINT NULL,
    type                  VARCHAR(255),
    sum                   FLOAT,
    FOREIGN KEY (financial_forecast_id)
        REFERENCES financial_forecast (id)
);

CREATE TABLE IF NOT EXISTS product_per_period
(
    product_id    BIGINT NULL,
    quantity      INT    NULL,
    for_export    FLOAT  NULL,
    price         FLOAT  NULL,
    cost_per_item FLOAT  NULL,
    year   INT    NULL,
    FOREIGN KEY (product_id)
        REFERENCES product (id)
)