DROP TABLE IF EXISTS financial_forecast CASCADE;
DROP TABLE IF EXISTS unit CASCADE ;
DROP TABLE IF EXISTS product CASCADE ;


CREATE TABLE IF NOT EXISTS financial_forecast
(
    id                         INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                       VARCHAR(255)  NOT NULL,
    selling_in_credit_rate     DECIMAL(5, 2) NULL,
    building_deprecation_rate  DECIMAL(5, 2) NULL,
    equipment_deprecation_rate DECIMAL(5, 2) NULL
);

CREATE TABLE IF NOT EXISTS unit
(
    id   INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS product
(
    id                    INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    financial_forecast_key INTEGER       NULL,
    unit_id               INTEGER       NULL,
    name                  VARCHAR(255)  NOT NULL,
    tax                   DECIMAL(5, 2) NOT NULL,
    stock_reserve_rate    DECIMAL(5, 2) NULL,
    CONSTRAINT fk_financial_forecast
        FOREIGN KEY (financial_forecast_key)
            REFERENCES financial_forecast (id),
    CONSTRAINT fk_unit
        FOREIGN KEY (unit_id)
            REFERENCES unit (id)
);
